### ISSUE TITLE
How exactly does the initial code run. what are the steps. 

### ISSUE THREAD

**Issue by chaitanya2334** [ankur-maximos/UDP-transfer#1]
I might come by your place sometime in the evening (arount 8pm today) to figure out how exactly the communication between the tcpd and the server/client works. And how the troll plays a role here.

**Comment by ankur-maximos** [comment]
Hey i will come late today(around 11PM), Can we have meeting tomorrow morning? I am free from morning until our demo starts.I am still working on it.We might have to do some debugging in morning..

**Comment by chaitanya2334** [comment]
Cool. I'll try to figure it out today. I can atleast get started on the send and receive functions
